plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '1.0'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}



dependencies {
    implementation 'io.muserver:mu-server:1.1.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0'
    testImplementation 'junit:junit:4.13.2'

    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'RestaurantBookingApp'
}

test {
    useJUnit()
}
